#!/usr/bin/env bash
clear
  
ENV=dev
  
PROJECT_ID=$(gcloud config list project --format "value(core.project)")
LOCATION=us-west1
BUCKET_NAME=< YOUR BUCKET-NAME >
GCS_FUSE_PATH='/gcs'
  
DOCKER_REPO=< YOUR DOCKER RPEO >
DOCKER_NAME=< YOUR DOCKER NAME >
DOCKER_VERSION=0.0.1
DOCKER_IMAGE_TAG="${LOCATION}-docker.pkg.${ENV}/${PROJECT_ID}/${DOCKER_REPO}/${DOCKER_NAME}:${DOCKER_VERSION}"
  
SERIVCE_ACCOUNT="shared-SERVICE-account@${PROJECT_ID}.iam.gserviceaccount.com"
  
VERTEX_AI_CUSTOM_JOB_SPEC='/tmp/vertex_custom_job_config.yaml'
DEVICE='cuda'
  
# Specify GPU Config in config yaml
GPU_TYPE = NVIDIA_TESLA_P100
GPU_COUNT = 1
 
cat << EOF > $VERTEX_AI_CUSTOM_JOB_SPEC
workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-8
      accelerator_type: $GPU_TYPE
      accelerator_count: $GPU_COUNT
    replicaCount: 1
    containerSpec:
      imageUri: $DOCKER_IMAGE_TAG
      command: ["python", "-m", "YOUR_PYTHON_MODULE", "COMMAND"]
      args:
        - --device_cpu_cuda=$DEVICE
        - --data_folder=../data/
        - --model-output-folder=/gcs/< BUCKET_NAME >  # Refer to GCSFuse Page
        - --num_epochs=1
        - --< PARAMS > .... ...
serviceAccount: $SERIVCE_ACCOUNT
EOF
cat $VERTEX_AI_CUSTOM_JOB_SPEC
  
DISPLAY_NAME="sharing-custom-trainig-$(date +"%Y%m%d%H%M%S")-$DEVICE"
echo "Display Name: $DISPLAY_NAME Service Account $SERIVCE_ACCOUNT"
  
gcloud ai custom-jobs create \
--region=$LOCATION \
--project=$PROJECT_ID \
--display-name=$DISPLAY_NAME \
--config=$VERTEX_AI_CUSTOM_JOB_SPEC \
--service-account=$SERIVCE_ACCOUNT
